# Generated by Django 5.0.6 on 2024-06-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='address_line1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='address_line2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='postcode',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='record',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
