# Generated by Django 5.0.6 on 2024-06-10 23:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_record_bio_alter_record_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
