# Generated by Django 5.0.6 on 2024-06-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_record_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
